name: Second Workflow

on:
  push:
    branches:
      - main

env:
  ENV1: "workflow-level-env"
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ENV2: "job-level-env"

    steps: 
      - name: say hello
        run: echo "Hello, World!"

      - name: use env variables
        run: echo "Application Environment is $APP_ENV (step-level-env), password is ${{ secrets.APP_PASSWORD }}"
        env:
          APP_ENV: "UAT"

      - name: use job level env variable
        run: echo "Job level environment variable is $ENV2, workflow level environment variable is $ENV1"